version: 0.2
env:
  variables:
    APP_NAME: "angular-cicd-pipeline-demo"
  parameter-store:
    GIT_REPO: "/codebuild/angular-aws-cicd-demo/github_repo"
phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - echo install process started
  pre-build:
    commands:
      - git clone $GIT_REPO APPDIR
      - cd APPDIR
      - git checkout main
  build:
    commands:
      - echo build process started now
      - npm install && npm install -g @angular/cli
      - ng build --configuration=production
  post-build:
    commands:
      - echo build process finished, we should uplload to S3 now
      - cd dist/$APP_NAME
      - ls -la

